# Site settings
title: Quyet blog
email: minhquyet@gmail.com
description: "Quyet blog"
baseurl: ""
url: "http://devcafe.info"
twitter_username: nmquyet
github_username: nmquyet

# Build settings
markdown: kramdown
permalink: pretty
