# Site settings
title: Devcafe Blog
email: minhquyet@gmail.com
description: "Sharing programming knowledge and experience"
baseurl: ""
url: "http://devcafe.info"
twitter_username: nmquyet
github_username: nmquyet

# Build settings
markdown: kramdown
permalink: pretty
